version: '3.1'
services:
  db:
    image: postgres:alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crypto
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8880:8080

  myredis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  zoo1:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888

  mykafka:
    image: confluentinc/cp-kafka:7.3.2
    hostname: mykafka
    container_name: mykafka
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://mykafka:9092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:19092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zoo1

  cryptorate:
    image: crypto-get-rate:latest
    restart: always
    container_name: crypto-get-rate
    environment:
      BINANCE_API_KEY: 
      BINANCE_SECRET: 
      KAFKA_URL: mykafka:9092
    depends_on:
      - mykafka

  cryptodb:
    image: crypto-set-db:latest
    restart: always
    container_name: crypto-set-db
    environment:
      DB_URL: "host=db port=5432 user=postgres dbname=crypto password=postgres sslmode=disable"
      KAFKA_URL: mykafka:9092
      REDIS_URL: myredis:6379
    depends_on:
      - mykafka
      - myredis
      - cryptorate
      - db

  cryptoapi:
    image: crypto-api:latest
    restart: always
    container_name: crypto-api
    ports:
      - "8080:8080"
    environment:
      DB_URL: "host=db port=5432 user=postgres dbname=crypto password=postgres sslmode=disable"
      REDIS_URL: myredis:6379
    depends_on:
      - cryptodb

